# Generated by Django 4.1.1 on 2022-12-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='subDiscribtion',
            field=models.TextField(default=1, max_length=3000),
            preserve_default=False,
        ),
    ]
