# Generated by Django 4.1.1 on 2022-12-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_subdiscribtion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='timing',
            field=models.DateField(),
        ),
    ]
