# Generated by Django 4.1.1 on 2022-12-06 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patientregister', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patientLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientregister.pactientaccount')),
            ],
        ),
    ]
