# Generated by Django 4.1.1 on 2022-12-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientlogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientlogin',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
