# Generated by Django 4.1.3 on 2022-12-07 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicalproviders', '0001_initial'),
        ('patientlogin', '0002_patientlogin_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicallogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('medicaldata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalproviders.medicalproviders')),
            ],
        ),
    ]
