# Generated by Django 4.1.1 on 2022-12-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('specialist', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('email_recption', models.CharField(blank=True, max_length=50, null=True)),
                ('years_of_experience', models.IntegerField(blank=True, max_length=2, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
    ]
