# Generated by Django 4.1.1 on 2022-12-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='email_recption',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
