# Generated by Django 4.1.1 on 2022-12-28 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctor_coverimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='coverimg',
        ),
    ]
