# Generated by Django 4.1.1 on 2022-12-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_remove_doctor_coverimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='photo'),
        ),
    ]
