# Generated by Django 4.1.1 on 2022-12-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_doctor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookedsession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('data', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
